"""empty message

Revision ID: 1efca6239691
Revises: 6cb9a7e43013
Create Date: 2020-11-06 15:29:11.229724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1efca6239691'
down_revision = '6cb9a7e43013'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=300), nullable=True))
        batch_op.alter_column('timezone',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('timezone',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###
